# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/trusty64"
  config.vm.network "private_network", ip: "192.168.33.112"

  config.vm.synced_folder "yandextank/", "/home/vagrant/yandextank"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant ansible slave"   
  #  vb.memory = "1024"
  end
  
  config.vm.define :Vagrant_ansible_slave do |t| # name машины в vagrant global-status
  end
  
  config.vm.provision "shell", path: '../provisions/provision_slave.sh'

end
