---
- hosts: test
  tasks:
     
    - name: install wget
      yum:
        name: wget
        state: present
        update_cache: yes
      become: true

    - name: Download java 8
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u121-b13/e9e7ea248e2c4826b92b3f075a80e441/jdk-8u121-linux-x64.rpm
        dest: /home/vagrant/jdk-8u121-linux-x64.rpm
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

    - name: Install java 8
      yum: 
        name=/home/vagrant/jdk-8u121-linux-x64.rpm
        state=present
        update_cache=yes
      become: true

    - name: Delete tmp files
      file:
        path=/home/vagrant/jdk-8u121-linux-x64.rpm
        state=absent