# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "centos/7"
  config.vm.network "private_network", ip: "192.168.33.127" # config.vm.network "public_network", ip: "192.168.0.127"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant ansible slave centos7 64"   

  end

  config.vm.define :Vagrant_ansible_slave_cos64 do |t| # name машины в vagrant global-status
  end

  config.vm.provision "shell", path: '../provisions/provision_slave.sh'

end
