---
- hosts: linux_centos
  tasks:
     
    - name: download java 7 x32 rpm
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/7u80-b15/jdk-7u80-linux-i586.rpm
        dest: /home/vagrant/jdk-7u80-linux-i586.rpm
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

    - name: install java 7 x32 rpm
      yum: 
        name=/home/vagrant/jdk-7u80-linux-i586.rpm
        state=present
      become: true

    - name: delete tmp files
      file:
        path=/home/vagrant/jdk-7u80-linux-i586.rpm
        state=absent