---
- hosts: linux_debian
  become: true
  tasks: 

  - name: Install apt-transport-https
    apt: 
      name={{item}}
      state=present
      update_cache=yes
    with_items:
      - apt-transport-https
      - python-apt

  - name: Add Grafana Repo
    apt_repository: 
      repo: 'deb https://packages.grafana.com/oss/deb stable main'
      state: present

  - name: Adding Grafana Repo Key
    apt_key:
      url: 'https://packages.grafana.com/gpg.key'
      state: present

  - name: Install grafana
    apt: 
      name: grafana
      state: present
      update_cache: yes

  - name: Start grafana-server service
    service:
      name: grafana-server
      state: started