- hosts: linux_debian
  become: true
  tasks: 

  - name: Install apt_key # установка для debian
    apt:
      name: software-properties-common
      state: present

  - name: Add mariadb key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
      state: present

  - name: Add mariadb repos
    apt_repository:
      repo: 'deb [arch=amd64,i386,ppc64el] ftp://ftp.ulak.net.tr/pub/MariaDB/repo/10.1/debian jessie main'
      state: present

  - name: Install mariadb
    apt:
      name: mariadb-server
      state: present
      update_cache: yes