---
- hosts: test # применяется для всех хостов
  become: yes
  tasks: # перечень задач

    - name: Install packages
      apt: 
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - python-pip
        - build-essential
        - python-dev
        - libffi-dev
        - gfortran
        - libssl-dev

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Upgrade setuptools
      pip:
        name: setuptools
        state: latest

    - name: Install yandex-tank
      pip: 
        name: https://api.github.com/repos/yandex/yandex-tank/tarball/master

    - name: Add phantom repository
      apt_repository: 
        repo: 'ppa:yandex-load/main'
        update_cache: yes

    - name: Install phantom
      apt: 
        name={{ item }}
        state=present
      with_items:
        - phantom
        - phantom-ssl