# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"
  config.vm.boot_timeout = 120
  config.vm.network "private_network", ip: "192.168.33.124"
  config.vm.synced_folder "yandextank/", "/home/vagrant/yandextank"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "Vagrant ansible slave debian 64"   
    vb.memory = "1024"
  end

  config.vm.define :Vagrant_ansible_slave_debian64 do |t| # name машины в vagrant global-status
  end

  config.vm.provision "shell", path: '../provisions/provision_slave.sh'

end
