# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "debian/jessie64"
  config.vm.boot_timeout = 120
  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.33.124"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder "yandextank/", "/home/vagrant/yandextank"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
    vb.memory = "3596"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtfR3M/T3HM0zwn06pawr6+pt+uyLpDtOWoWIog4Z59BknNOz+DfsqSETx7nLFUxv8Wqogc5NO/wyud1LT8eyypLKi0CMqYpdmTWsIdFMaEnryIThySPFVArljHrVekrB1cHY6/9ou7L3Ff6PLu59q/+1WPBcWxJ4QUwfvqsVasDqBndH5HOWInwuV/iyCXXupjKQwpkL34UpxZw6esird4DojNXrsxEmvhVlNG5doqo5unvmu/k6/l0hE34+JmM5Ve35watm+0VfLcIjmSsr1ALeJR6jGJ+cmuO8ptc8PnJEGvuJrrwIGSmgxCAb1fqYDgnhohP1TmEL/WqsgQ9r/ vagrant@vagrant-ubuntu-trusty-64" >> /home/vagrant/.ssh/authorized_keys
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAgLwj3Jq5QAmZX7B/8Of6y+2wt485hiThkrJ34OBmSg/2N4AvjP+Hlo/edwFRryD1mtFT2mPrilqQ2ElJKoIgzDYsx3izzkLNAK5ii0JLVZjmZeyHueQMwzxz80cwVjpn8kPqGYw3y4JVBhFljcbhFprqGJgogyHMq5t6spGv9k3QGbqRTgAGmoKvhcCCfUHtLJHDc/++uMuknjuA7Kvb4zby7ZDMYbYF27AJMBK6Tvi2DJsFepm8BnGIcywA0EQ3ym5NeEU6TNgXmRiFyEoQDc16cihW25K5Y0Ab2M/tnoHw+x9CrUhMr6CR+cTq6OIaY1fLdqyI/HBCLQUvcccwuQ== rsa-key-20160609" >> /home/vagrant/.ssh/authorized_keys
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDK7uopgJtFfeXVGRUqdgVrxsQlnVf45nSAqY+y/A4d0NiXpir74aax9t/zsIeTYC2mvmeGCFy71HMM956OJCUOWH5IY6tSOgc2TkboPxcz5UmQZyJ1yP9I6yX1w4qMQQ5qyNHMgfwIcZCPjiZjTih7Fe/YgWSYuwr/XBw30komNNx3ODpHR3wBx/tyw2JYroTfUGjS94JwihfM+VjdhECcgIAcfjhdvHDL1o0M3tW0JVdUUIBdbH2NT7HSOa56bnyS8aaF5MEhe4XlsTdHSNyMaRNSKn08YeZcjpb6YMYYNlupofVp+oiOLQ7zq/A/XCPMPs66p2tGqCN1+yKmYjAh vagrant@jessie" >> /home/vagrant/.ssh/authorized_keys
  SHELL
end
