---
- hosts: test
  become: true
  tasks: 

    - name: Install pip 
      apt:
        name: python-pip
        state: present

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Install sphinx
      pip:
        name: sphinx
        state: latest
