---
- hosts: linux_debian
  become: true
  tasks:

    - name: Install dependences
      apt:
        name: ['git', 'python3', 'python3-pip']
        state: present
        update_cache: yes

    - name: update pip
      pip:
        name: ['pip', 'setuptools']
        state: latest
        executable: pip3

    - name: install locust
      pip:
        name: git+http://github.com/locustio/locust.git@master#egg=locustio
        state: present
        executable: pip3