---
- hosts: linux_debian
  become: true
  tasks:

    - name: Install dependences
      apt:
        name={{item}}
        state=present
        update_cache=yes
      with_items:
        - git
        - python3
        - python3-pip

    - name: update pip
      pip:
        name={{item}}
        state=latest
        executable=pip3
      with_items:
        - pip
        - setuptools

    - name: install locust
      pip:
        name: git+http://github.com/locustio/locust.git@master#egg=locustio
        state: present
        executable: pip3