---
- hosts: linux_debian # применяется для всех хостов
  become: yes
  tasks: # перечень задач

    - name: Install packages
      apt: 
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - python-pip
        - build-essential
        - python-dev
        - libffi-dev
        - gfortran
        - libssl-dev

    - name: Install packages for debian # только для debian
      apt: 
        name={{ item }}
        state=present
        update_cache=yes
      with_items:
        - binutils-dev
        - git
      when: ansible_distribution == "Debian"

    - name: Upgrade pip
      pip:
        name: pip
        state: latest

    - name: Upgrade setuptools
      pip:
        name: setuptools
        state: latest

    - name: Install yandex-tank
      pip: 
        name: https://api.github.com/repos/yandex/yandex-tank/tarball/master

    - name: Add phantom repository # только для Ubuntu
      apt_repository: 
        repo: 'ppa:yandex-load/main'
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: Install phantom # только для Ubuntu
      apt: 
        name={{ item }}
        state=present
      with_items:
        - phantom
        - phantom-ssl
      when: ansible_distribution == "Ubuntu"

    - name: Clone phantom from github
      git:
        repo: https://github.com/mamchits/phantom.git
        dest: /home/vagrant/phantom
      when: ansible_distribution == "Debian"
      become: no
      
    - name: make
      command: make -R all
      args:
        chdir: /home/vagrant/phantom
      when: ansible_distribution == "Debian"
      become: no

    - name: move 1
      command: mv /home/vagrant/phantom/bin/phantom /usr/bin/
      when: ansible_distribution == "Debian"

    - name: move 2
      command: mv /home/vagrant/phantom/lib/phantom/ /usr/lib/
      when: ansible_distribution == "Debian"