- hosts: linux_debian
  become: true
  tasks: 

  - name: Add repos postgresql # установка для debian jessie
    apt_repository:
      repo: 'deb http://apt.postgresql.org/pub/repos/apt/ jessie-pgdg main'
      state: present
      filename: 'pgdg'

  - name: Add apt key postgresql
    apt_key: 
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      state: present

  - name: Install postgresql
    apt:
      name: postgresql-9.6
      state: present
      update_cache: yes
