---
- hosts: linux_debian
  tasks:

  - name: Send notification message via Slack
    slack:
      domain: # your_domain
      token: # your_token
      #channel: @your_channel # если добавлен только в один личный канал то не нужно
      msg: '{{ inventory_hostname }} completed'
    # delegate_to: localhost # не уверен что вообще нужно