---
- hosts: linux_debian
  become: true
  tasks:

    - name: Add jenkins user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%jenkins ALL='
        line: '%jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Download jenkins-cli
      get_url:
        url: http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
        dest: /home/vagrant/jenkins-cli.jar
      become: false

    #- name: Copy vegeta job config
    #  shell: scp /home/vagrant/ansible/playbooks/debian/jenkins/config.xml vagrant@192.168.33.124:/home/vagrant/config.xml
    #  become: false

    #- name: Create jenkins job vegeta
    #  shell: java -jar /home/vagrant/jenkins-cli.jar -s http://127.0.0.1:8080/ create-job vegeta < /home/vagrant/config.xml --username admin --password admin

    - name: Start jenkins job vegeta
      shell: java -jar /home/vagrant/jenkins-cli.jar -s http://127.0.0.1:8080/ build vegeta --username admin --password admin