---
- hosts: linux_debian
  become: true
  tasks:

    - name: Add jenkins user to sudoers
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%jenkins ALL='
        line: '%jenkins ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Download jenkins-cli
      get_url:
        url: http://127.0.0.1:8080/jnlpJars/jenkins-cli.jar
        dest: /home/vagrant/jenkins-cli.jar
      become: false