---
- hosts: linux_debian
  become: true
  tasks:

    #- name: Jenkins - configure | Turn off Jenkins setup wizard
    #  lineinfile: 
    #    dest: /etc/default/jenkins
    #    regexp: '^JAVA_ARGS=' 
    #    line: 'JAVA_ARGS="-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"'
    #  # notify: restart jenkins

    - name: 
      lineinfile:
        path: /var/lib/jenkins/config.xml
        regexp: '<authorizationStrategy class="hudson.security.FullControlOnceLoggedInAuthorizationStrategy">'
        line: '<authorizationStrategy class="hudson.security.AuthorizationStrategy$Unsecured"/>'

    - name: 
      lineinfile:
        path: /var/lib/jenkins/config.xml
        regexp: '<denyAnonymousReadAccess>false</denyAnonymousReadAccess>'
        state: absent

    - name: 
      lineinfile:
        path: /var/lib/jenkins/config.xml
        regexp: '</authorizationStrategy>'
        state: absent
      