# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  config.vm.define :master_ansible do |master| # name машины в vagrant global-status
  
  	master.vm.box = "ubuntu/trusty64"
  	master.vm.network "private_network", ip: "192.168.33.12"
	  master.vm.synced_folder "ansible/", "/etc/ansible"
  	master.vm.synced_folder "playbooks/", "/home/vagrant/ansible/playbooks"
  	master.vm.synced_folder ".ssh/", "/home/vagrant/.ssh", owner: "vagrant", group: "vagrant", mount_options: ["dmode=700,fmode=600"]
    config.vm.provider "virtualbox" do |vb|
  	  vb.name = "ansible master" 
  	end
	
	  config.vm.provision "shell", inline: <<-SHELL
  	  sudo apt-get update
    	sudo apt-get install -y python-pip python-software-properties software-properties-common python-jinja2 python-markupsafe yum
    	sudo pip install ansible
  	SHELL
	end

	config.vm.define :debian_ansible_slave do |debian|
	
		debian.vm.box = "debian/jessie64"
  	debian.vm.boot_timeout = 120
  	debian.vm.network "private_network", ip: "192.168.33.124"
  	debian.vm.synced_folder "yandextank/", "/home/vagrant/yandextank"
  	config.vm.provider "virtualbox" do |vb|
  		vb.name = "vagrant debian"
  		vb.memory = "3596"
  	end

  	config.vm.provision "shell", inline: <<-SHELL
  		echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDtfR3M/T3HM0zwn06pawr6+pt+uyLpDtOWoWIog4Z59BknNOz+DfsqSETx7nLFUxv8Wqogc5NO/wyud1LT8eyypLKi0CMqYpdmTWsIdFMaEnryIThySPFVArljHrVekrB1cHY6/9ou7L3Ff6PLu59q/+1WPBcWxJ4QUwfvqsVasDqBndH5HOWInwuV/iyCXXupjKQwpkL34UpxZw6esird4DojNXrsxEmvhVlNG5doqo5unvmu/k6/l0hE34+JmM5Ve35watm+0VfLcIjmSsr1ALeJR6jGJ+cmuO8ptc8PnJEGvuJrrwIGSmgxCAb1fqYDgnhohP1TmEL/WqsgQ9r/ vagrant@vagrant-ubuntu-trusty-64" >> /home/vagrant/.ssh/authorized_keys
    	echo "ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAgLwj3Jq5QAmZX7B/8Of6y+2wt485hiThkrJ34OBmSg/2N4AvjP+Hlo/edwFRryD1mtFT2mPrilqQ2ElJKoIgzDYsx3izzkLNAK5ii0JLVZjmZeyHueQMwzxz80cwVjpn8kPqGYw3y4JVBhFljcbhFprqGJgogyHMq5t6spGv9k3QGbqRTgAGmoKvhcCCfUHtLJHDc/++uMuknjuA7Kvb4zby7ZDMYbYF27AJMBK6Tvi2DJsFepm8BnGIcywA0EQ3ym5NeEU6TNgXmRiFyEoQDc16cihW25K5Y0Ab2M/tnoHw+x9CrUhMr6CR+cTq6OIaY1fLdqyI/HBCLQUvcccwuQ== rsa-key-20160609" >> /home/vagrant/.ssh/authorized_keys
  	SHELL
  end
end
