---
- hosts: linux_debian
  become: true
  tasks: 

    - name: Install Elasticsearch 
      apt:
        deb: https://download.elastic.co/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.4.4/elasticsearch-2.4.4.deb
        state: present
