---
- hosts: linux_debian
  become: true
  tasks: 
  - name: Install add-apt-repository
    apt: 
      name={{item}}
      state=latest
      update_cache=yes
    with_items:
      - apt-transport-https
      - ca-certificates

  - name: Add Oracle Java Repository
    apt_repository: 
      repo: 'deb https://apt.dockerproject.org/repo debian-jessie main'
      state: present
      filename: docker

  - name: Adding Oracle Java9 Repo Key
    apt_key:
      keyserver: 'hkp://p80.pool.sks-keyservers.net:80'
      id: '58118E89F3A912897C070ADBF76221572C52609D'
      state: "present"

  - name: Install docker
    apt:
      name: docker-engine
      state: latest
      update_cache: yes

  - name: docker group add
    group: 
      name: docker
      state: present

  - name: add user to group 
    user:
      name: vagrant
      groups: docker
      append: yes

  - name: start docker 
    service:
      name: docker
      state: started