---
- hosts: linux_debian
  become: true
  tasks: 

  - name: apt update && upgrade
    apt: 
      force_apt_get: yes
      only_upgrade: yes
      update_cache: yes

  - name: install packages
    apt: 
      name: "{{ packages }}"
      force_apt_get: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl 
        - software-properties-common
        - gnupg2

  - name: Adding Repo Key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg

  - name: add docker repo
    apt_repository: 
      repo: 'deb [arch=amd64] https://download.docker.com/linux/debian stretch stable'
      state: present
      filename: docker

  - name: Install docker
    apt:
      name: docker-ce
      state: latest
      update_cache: yes

  # - name: docker group add
  #   group: 
  #     name: docker
  #     state: present

  - name: add user to group 
    user:
      name: vagrant
      groups: docker
      append: yes

  # - name: start docker 
  #   service:
  #     name: docker
  #     state: started

  - name: change file 
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver'
      line: nameserver 8.8.8.8