---
- hosts: linux_centos
  tasks:
     
    - name: install wget
      yum:
        name: wget
        state: present
        update_cache: yes
      become: true

    - name: Download java 8
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u131-b11/d54c1d3a095b4ff2b6607d096fa80163/jdk-8u131-linux-x64.rpm
        dest: /home/vagrant/jdk-8u131-linux-x64.rpm
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'

    - name: Install java 8
      yum: 
        name=/home/vagrant/jdk-8u131-linux-x64.rpm
        state=present
        update_cache=yes
      become: true

    - name: Delete tmp files
      file:
        path=/home/vagrant/jdk-8u131-linux-x64.rpm
        state=absent
        