---
- hosts: test
  tasks: 

    - name: Download and unarchive Apache-maven # вариант с скачиванием и распаковкой в одной задаче
      unarchive:
        src: http://apache.volia.net/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz
        dest: /home/vagrant/
        remote_src: True
        validate_certs: False

    - name: add M2_HOME
      lineinfile:
        dest: "/home/vagrant/.profile"
        regexp: '^M2_HOME=' # не уверен что строка тут нужна, проверить и возможно убрать
        line: 'export M2_HOME=/home/vagrant/apache-maven-3.3.9'
      
    - name: add PATH
      lineinfile:
        dest: /home/vagrant/.profile
        regexp: '^PATH=' # не уверен что строка тут нужна, проверить и возможно убрать
        line: 'export PATH=${PATH}:${M2_HOME}/bin'

    - name: source .profile
      command: /home/vagrant/.profile
      args:
        executable: /bin/bash