---
- hosts: linux_debian
  become: true
  tasks:

  - name: Add sublime key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present

  - name: Install apt-transport-https
    apt:
      name: apt-transport-https
      state: present
      update_cache: yes

  - name: Create repofile
    file:
      path: /etc/apt/sources.list.d/sublime-text.list
      state: touch

  - name: Add line
    lineinfile:
      path: /etc/apt/sources.list.d/sublime-text.list
      line: 'deb https://download.sublimetext.com/ apt/stable/'
      state: present

  - name: Install siblime-text
    apt:
      name: sublime-text
      state: present
      update_cache: yes