---
- hosts: test
  become: true
  tasks: 
      
    - name: Configure Kibana
      blockinfile:
        dest: /etc/kibana/kibana.yml
        block: |
          server.port: 5601
          server.host: 0.0.0.0
