---
- hosts: test
  become: true
  tasks: 

    - name: Install Kibana 
      apt:
        deb: https://artifacts.elastic.co/downloads/kibana/kibana-5.2.2-amd64.deb
        state: present
      
    - name: Configure Kibana
      blockinfile:
        dest: /etc/kibana/kibana.yml
        block: |
          server.port: 5601
          server.host: 0.0.0.0

    - name: Start service Kibana
      service: 
        name: kibana
        state: started