---
- hosts: test
  tasks:
   
    - name: check java-package
      apt:
        name=java-package
        state=present
        update_cache=yes
      become: true

    - name: download java 8 x64
      get_url:
        url: http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jdk-8u112-linux-x64.tar.gz
        dest: /home/vagrant/jdk-8u112-linux-x64.tar.gz
        headers: 'Cookie: oraclelicense=accept-securebackup-cookie'
        
    - name: make java8.deb
      raw: echo "Y" > Yes_package
    
    - name: make java8.deb 2
      raw:  make-jpkg jdk-8u112-linux-x64.tar.gz < Yes_package

    - name: rm temp files
      file: 
        path=/home/vagrant/Yes_package
        state=absent

    - name: install java 8
      apt: 
        deb=/home/vagrant/oracle-java8-jdk_8u112_amd64.deb
        state=present
      become: true

    - name: remove tmp files java8.tar.gz
      file:
        path=/home/vagrant/jdk-8u112-linux-x64.tar.gz
        state=absent

    - name: remove tmp files java8.deb
      file: 
        path=/home/vagrant/oracle-java8-jdk_8u112_amd64.deb
        state=absent

    - name: remove java-package
      apt: 
        name=java-package
        state=absent
      become: true
