---
- hosts: linux_centos
  become: true
  tasks:

    - name: unistall java rpm
      yum:
        name={{ item }}
        state=absent
      with_items:
        - jdk.i586 # java 6 or 7 x32
        - jdk1.8.0_101.i586 # java 8 x32
        - jdk.x86_64 # java 6 x64
        - jre.x86_64 # java 7 jre x64
        - jdk1.8.0_121.x86_64 # java 8 x64
